"""
Trading Signal Model

Represents a trading signal generated by a strategy.
"""

from pydantic import BaseModel, Field
from typing import Literal


class Signal(BaseModel):
    """
    Trading signal generated by a strategy.

    Attributes:
        action: Trading action (BUY or SELL)
        confidence: Signal confidence level (0.0 to 1.0, typically 0.7-0.9)

    Example:
        >>> signal = Signal(action="BUY", confidence=0.85)
        >>> print(signal.action)  # "BUY"
        >>> print(signal.confidence)  # 0.85
    """

    action: Literal["BUY", "SELL"] = Field(
        description="Trading action (BUY or SELL)"
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Signal confidence (0.0 to 1.0, typically 0.7-0.9)"
    )

    def __repr__(self) -> str:
        return f"Signal(action={self.action}, confidence={self.confidence:.2f})"
