package com.quantstream.strategy.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Represents a trading signal generated by a strategy.
 * 
 * This is the OUTPUT of strategy analysis - produced to Kafka
 * and consumed by signal-aggregator service.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Signal {
    private String symbol;         // Which asset (AAPL, BTC, etc.)
    private String action;         // BUY, SELL, or HOLD
    private String strategyName;   // Which strategy generated this (MA_CROSSOVER, RSI, etc.)
    private double confidence;     // Confidence score 0.0 to 1.0
    private Instant timestamp;     // When signal was generated
}