package com.quantstream.consumer.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.Instant;

/**
 * Represents a trading signal generated by the strategy engine.
 * 
 * Received from Kafka topic: trading-signals (produced by strategy-engine)
 * Stored in QuestDB table: signals
 * 
 * Fields:
 * - symbol: Stock/crypto symbol being signaled
 * - action: Trading action (BUY, SELL, HOLD)
 * - strategyName: Which strategy generated this signal (e.g., MovingAverageCrossover)
 * - confidence: Signal strength (0.0 to 1.0, where 1.0 = highest confidence)
 * - timestamp: When the signal was generated
 * 
 * Example:
 * {
 *   "symbol": "AAPL",
 *   "action": "BUY",
 *   "strategyName": "MovingAverageCrossover",
 *   "confidence": 0.85,
 *   "timestamp": "2026-07-19T01:45:00Z"
 * }
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class Signal {
    
    private String symbol;
    private String action;           // BUY, SELL, HOLD
    private String strategyName;     // Which strategy generated this
    private double confidence;       // 0.0 to 1.0
    private Instant timestamp;
}